const bankTemplates = {
  SBI: {
    name: "State Bank of India",
    color: "#1a237e",
    accent: "#2196f3",
    backgroundImage: "/Images/sbi-cheque.jpg",
    chequeWidth: "204mm",
    chequeHeight: "93mm",
    dateTop: "6mm",
    dateRight: "9mm",
    dateWidth: "40mm",
    dateHeight: "5mm",
    dateGap: "0mm",
    dateCharWidth: "5mm",
    dateFontSize: "10pt",
    payeeTop: "22mm",
    payeeLeft: "35mm",
    payeeWidth: "144mm",
    payeeHeight: "5mm",
    payeeFontSize: "11.5pt",
    amountWordsTop: "32mm",
    amountWordsLeft: "35mm",
    amountWordsWidth: "144mm",
    amountWordsHeight: "15mm",
    amountWordsFontSize: "10pt",
    amountBoxTop: "38mm",
    amountBoxLeft: "157mm",
    amountBoxWidth: "45mm",
    amountBoxHeight: "8mm",
    amountBoxMinWidth: "0",
    amountBoxFontSize: "12pt",
    showAmountPrefix: true,
    showGuideLines: false,
    showAmountBoxBorder: false,
    acPayeeTop: "17mm",
    acPayeeLeft: "12mm",
    showSignatureGuide: false,
    showMicrHint: false,
  },
  INDIAN: {
    name: "Indian Bank",
    color: "#0f5b78",
    accent: "#f0c02b",
    backgroundImage: "/Images/indian-cheque.jpg",
    dateTop: "8mm",
    dateRight: "8mm",
    dateWidth: "32mm",
    payeeTop: "27mm",
    payeeLeft: "23mm",
    payeeWidth: "138mm",
    amountWordsTop: "39mm",
    amountWordsLeft: "18mm",
    amountWordsWidth: "132mm",
    amountBoxTop: "39mm",
    amountBoxRight: "31mm",
    amountBoxMinWidth: "30mm",
    showAmountPrefix: false,
    acPayeeTop: "17mm",
    acPayeeLeft: "12mm",
  },
  HDFC: {
    name: "HDFC Bank",
    color: "#004c8f",
    accent: "#e31837",
    backgroundImage: "/Images/hdfc-cheque.jpg",
    dateTop: "10mm",
    dateRight: "14mm",
    dateWidth: "34mm",
    payeeTop: "27mm",
    payeeLeft: "30mm",
    payeeWidth: "150mm",
    amountWordsTop: "42mm",
    amountWordsLeft: "20mm",
    amountWordsWidth: "122mm",
    amountBoxTop: "41mm",
    amountBoxRight: "12mm",
    amountBoxMinWidth: "28mm",
    showAmountPrefix: true,
    acPayeeTop: "19mm",
    acPayeeLeft: "14mm",
  },
  ICICI: {
    name: "ICICI Bank",
    color: "#b71c1c",
    accent: "#f57c00",
    backgroundImage: "/Images/icici-cheque.jpg",
    chequeWidth: "204mm",
    chequeHeight: "93mm",
    dateTop: "6mm",
    dateRight: "9mm",
    dateWidth: "40mm",
    dateHeight: "5mm",
    dateGap: "0mm",
    dateCharWidth: "5mm",
    payeeTop: "22mm",
    payeeLeft: "35mm",
    payeeWidth: "144mm",
    payeeHeight: "5mm",
    amountWordsTop: "32mm",
    amountWordsLeft: "35mm",
    amountWordsWidth: "144mm",
    amountWordsHeight: "15mm",
    amountBoxTop: "38mm",
    amountBoxLeft: "157mm",
    amountBoxWidth: "45mm",
    amountBoxHeight: "8mm",
    amountBoxMinWidth: "0",
    showAmountPrefix: true,
    showGuideLines: false,
    acPayeeTop: "17mm",
    acPayeeLeft: "12mm",
  },
  AXIS: {
    name: "Axis Bank",
    color: "#800020",
    accent: "#c62828",
    backgroundImage: "/Images/axis-cheque.jpg",
    dateTop: "9mm",
    dateRight: "13mm",
    dateWidth: "34mm",
    payeeTop: "26mm",
    payeeLeft: "27mm",
    payeeWidth: "150mm",
    amountWordsTop: "41mm",
    amountWordsLeft: "20mm",
    amountWordsWidth: "124mm",
    amountBoxTop: "40mm",
    amountBoxRight: "13mm",
    amountBoxMinWidth: "28mm",
    showAmountPrefix: true,
    acPayeeTop: "18mm",
    acPayeeLeft: "13mm",
  },
  PNB: {
    name: "Punjab National Bank",
    color: "#1b5e20",
    accent: "#ff6f00",
    backgroundImage: "/Images/pnb-cheque.jpg",
    dateTop: "9mm",
    dateRight: "12mm",
    dateWidth: "34mm",
    payeeTop: "26mm",
    payeeLeft: "26mm",
    payeeWidth: "150mm",
    amountWordsTop: "42mm",
    amountWordsLeft: "20mm",
    amountWordsWidth: "123mm",
    amountBoxTop: "41mm",
    amountBoxRight: "12mm",
    amountBoxMinWidth: "28mm",
    showAmountPrefix: true,
    acPayeeTop: "18mm",
    acPayeeLeft: "13mm",
  },
  KVB: {
    name: "Karur Vysya Bank",
    color: "#004b8d",
    accent: "#f5a623",
    backgroundImage: "/Images/kvb-cheque.jpg",
    dateTop: "9mm",
    dateRight: "12mm",
    dateWidth: "34mm",
    payeeTop: "26mm",
    payeeLeft: "28mm",
    payeeWidth: "150mm",
    amountWordsTop: "41mm",
    amountWordsLeft: "20mm",
    amountWordsWidth: "125mm",
    amountBoxTop: "40mm",
    amountBoxRight: "12mm",
    amountBoxMinWidth: "28mm",
    showAmountPrefix: true,
    acPayeeTop: "18mm",
    acPayeeLeft: "14mm",
  },
};

export default bankTemplates;
